# Generated by Django 4.2.8 on 2024-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('wooman', 'wooman')], default='male', max_length=6),
        ),
    ]
