# Generated by Django 4.2.8 on 2024-03-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_year',
            field=models.IntegerField(default=None),
        ),
    ]
