# Generated by Django 4.2.8 on 2024-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_birth_year_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
