# Generated by Django 4.2.7 on 2023-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometric',
            name='add',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='ads',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='chs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='left_hand_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='right_hand_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='vital_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
