# Generated by Django 4.2.7 on 2023-12-06 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_alter_anthropometric_add_alter_anthropometric_ads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('genchi', models.FloatField(blank=True, null=True)),
                ('shtange', models.FloatField(blank=True, null=True)),
                ('functional_ccc', models.FloatField(blank=True, null=True)),
                ('orthostatic', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
