# Generated by Django 4.2.7 on 2023-12-10 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_functional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('run', models.FloatField(blank=True, null=True)),
                ('incline', models.FloatField(blank=True, null=True)),
                ('bending', models.FloatField(blank=True, null=True)),
                ('raising', models.FloatField(blank=True, null=True)),
                ('pull_up', models.FloatField(blank=True, null=True)),
                ('squat', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
