# Generated by Django 4.2.8 on 2024-03-13 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_physicalstandards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(blank=True, null=True)),
                ('sleep', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('appetite', models.IntegerField(blank=True, null=True)),
                ('pain', models.IntegerField(blank=True, null=True)),
                ('overload', models.IntegerField(blank=True, null=True)),
                ('perfomance', models.IntegerField(blank=True, null=True)),
                ('loads_attitude', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
